### ISSUE TITLE
Remove/Change subclassing of NETN Human and NETN Platform Object Classes 

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-CBRN#3]
Attributes in the subclasses can either be included in the corresponding NETN classes in the NETN-Physical FOM module or if the new HLA 4 FOM merging rules can be applied the attributes should be defined as extensions to the existing NETN classes. Both changes will constitute a major change.

**Comment by lofstrandbjorn** [comment]
Attributes added in CBRN Module on Human Class using HLA4 FOM Merging rules.
