### ISSUE TITLE
Consider moving CBRN interaction classes as subclasses of CBRN_Root class

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-CBRN#4]
FOM module specific interactions are in other NETN Modules placed as subclasses of a Root or Base class for that module.

**Comment by lofstrandbjorn** [comment]
Check with MSG-147 and UK

**Comment by lofstrandbjorn** [comment]
Harmonize with proposed Disaster Module DIM

**Comment by lofstrandbjorn** [comment]
New proposed update uses SMC and DIM class structures
