### ISSUE TITLE
Harmonize data types

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-CBRN#9]
See https://github.com/AMSP-04/NETN-BASE/issues/1

**Comment by linusonline** [comment]
Propose:

- Remove simple data type ConcentrationKgPerMeterCubedFloat32 (add to BASE)

**Comment by lofstrandbjorn** [comment]
* Removed SimpleDatatype ´ConcentrationKgPerMeterCubedFloat32´ (move to NETN-BASE)
* Changed use of data type ´TimeSecInt64´ to ´EpochTimeSecInt64´ (renamed in NETN-BASE)
